# Generated by Django 4.2.7 on 2025-11-27 01:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Merchant",
            fields=[
                (
                    "merchant_id",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "merchants",
            },
        ),
        migrations.CreateModel(
            name="UploadTask",
            fields=[
                (
                    "task_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField()),
                ("rows_processed", models.BigIntegerField(default=0)),
                ("rows_failed", models.BigIntegerField(default=0)),
                ("processing_time", models.FloatField(blank=True, null=True)),
                ("memory_usage", models.FloatField(blank=True, null=True)),
                ("throughput", models.FloatField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "upload_tasks",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("merchant_id", models.CharField(db_index=True, max_length=100)),
                ("zone", models.CharField(db_index=True, max_length=100)),
                ("category", models.CharField(db_index=True, max_length=100)),
                (
                    "amount",
                    models.DecimalField(db_index=True, decimal_places=2, max_digits=12),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("customer_phone", models.CharField(db_index=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "transactions",
                "indexes": [
                    models.Index(
                        fields=["zone", "amount"], name="transaction_zone_773e38_idx"
                    ),
                    models.Index(
                        fields=["category", "amount"],
                        name="transaction_categor_3249d8_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="transaction_timesta_07633a_idx"
                    ),
                    models.Index(
                        fields=["customer_phone"], name="transaction_custome_9a3a12_idx"
                    ),
                ],
            },
        ),
    ]
