# Generated by Django 4.2.7 on 2025-11-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uploadtask",
            old_name="memory_usage",
            new_name="cache_hit_rate",
        ),
        migrations.RenameField(
            model_name="uploadtask",
            old_name="processing_time",
            new_name="peak_memory_mb",
        ),
        migrations.RenameField(
            model_name="uploadtask",
            old_name="throughput",
            new_name="processing_rate_rows_per_sec",
        ),
        migrations.RenameField(
            model_name="uploadtask",
            old_name="rows_failed",
            new_name="rows_rejected",
        ),
        migrations.AddField(
            model_name="uploadtask",
            name="db_query_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="uploadtask",
            name="execution_time_ms",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="uploadtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUEUED", "Queued"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="QUEUED",
                max_length=20,
            ),
        ),
    ]
